### ISSUE TITLE
Virtual environment 

### ISSUE THREAD

**Issue by ghost** [tomaratyn/MailApe#1]
@tomaratyn

Thanks for your excellent book and I am about to start following your tutorial. However, I have a concern. I have noticed that you did not create a virtual environment for your MailApe software, May I know why? I will be building this app on my Windows 10 machine and I don't want to mess up with my other app's dependencies. So, if I build this on virtual environment, should I face any issues during deployment?

Appreciate your response. 

Regards

**Comment by tomaratyn** [comment]
I'm glad you enjoyed the book, @armaanreza.

I don't talk about virtual environments for two reasons:

 1. Virtual env (or pyenv) are standard for Python developers and this book assumes familiarity with Python.

 2. I was over the page count by a lot already. So I decided to cut out stuff that I could assume people are already using.

Just to be clear: you should definitely use a virtual env. Always. The same way you start a separate code repo for each project, you should also have start a separate virtual env too. 

Cheers!

**Comment by ghost** [comment]
Thanks @tomaratyn
